
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cesar31.formsweb.lexerandparser;

/** CUP generated class containing symbol constants. */
public class FormsParserSym {
  /* terminals */
  public static final int DEL_USER = 12;
  public static final int LOGIN = 13;
  public static final int RBRACE = 20;
  public static final int DATE = 10;
  public static final int GREATER = 18;
  public static final int INIT_MANY_SOL = 4;
  public static final int USER = 8;
  public static final int PASS = 9;
  public static final int LBRACKET = 21;
  public static final int LBRACE = 19;
  public static final int COLON = 17;
  public static final int INIT_SOL = 2;
  public static final int CRED = 7;
  public static final int ID = 15;
  public static final int RBRACKET = 22;
  public static final int PARAMQ = 14;
  public static final int QUOTE = 16;
  public static final int COMMA = 23;
  public static final int EDIT_USER = 11;
  public static final int EOF = 0;
  public static final int FIN_MANY_SOL = 5;
  public static final int error = 1;
  public static final int FIN_SOL = 3;
  public static final int NEW_USER = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INIT_SOL",
  "FIN_SOL",
  "INIT_MANY_SOL",
  "FIN_MANY_SOL",
  "NEW_USER",
  "CRED",
  "USER",
  "PASS",
  "DATE",
  "EDIT_USER",
  "DEL_USER",
  "LOGIN",
  "PARAMQ",
  "ID",
  "QUOTE",
  "COLON",
  "GREATER",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "COMMA"
  };
}

