
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cesar31.formsweb.parser.sqf;

/** CUP generated class containing symbol constants. */
public class SQFParserSym {
  /* terminals */
  public static final int TIMES = 21;
  public static final int WHERE = 6;
  public static final int APOS = 25;
  public static final int AND = 9;
  public static final int PLUS = 19;
  public static final int OR = 10;
  public static final int SMALLER = 13;
  public static final int DECIMAL = 29;
  public static final int FM = 4;
  public static final int NOT = 11;
  public static final int ERROR = 27;
  public static final int GREATER = 12;
  public static final int GR_EQ = 14;
  public static final int LBRACKET = 7;
  public static final int ID = 23;
  public static final int RBRACKET = 8;
  public static final int COMMA = 18;
  public static final int EOF = 0;
  public static final int DIVIDE = 22;
  public static final int MINUS = 20;
  public static final int error = 1;
  public static final int ARROW = 5;
  public static final int VALUE_STR = 26;
  public static final int STR = 24;
  public static final int EQ = 16;
  public static final int SEL = 2;
  public static final int INTEGER = 28;
  public static final int NEQ = 17;
  public static final int TO = 3;
  public static final int SM_EQ = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEL",
  "TO",
  "FM",
  "ARROW",
  "WHERE",
  "LBRACKET",
  "RBRACKET",
  "AND",
  "OR",
  "NOT",
  "GREATER",
  "SMALLER",
  "GR_EQ",
  "SM_EQ",
  "EQ",
  "NEQ",
  "COMMA",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "ID",
  "STR",
  "APOS",
  "VALUE_STR",
  "ERROR",
  "INTEGER",
  "DECIMAL"
  };
}

