
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cesar31.formsweb.parser.db;

/** CUP generated class containing symbol constants. */
public class DataParserSym {
  /* terminals */
  public static final int LBRACKET = 4;
  public static final int TIPO = 26;
  public static final int STR = 35;
  public static final int INTEGER = 38;
  public static final int USERS = 3;
  public static final int ROWS = 33;
  public static final int USER_C = 20;
  public static final int ID_FORM = 16;
  public static final int PASS = 12;
  public static final int COMMA = 9;
  public static final int REQUIRED = 30;
  public static final int COMP = 22;
  public static final int FIELD_N = 24;
  public static final int EOF = 0;
  public static final int RBRACKET = 5;
  public static final int TRUE = 36;
  public static final int error = 1;
  public static final int NULL = 15;
  public static final int FORM_ID = 25;
  public static final int URL = 31;
  public static final int NAME = 18;
  public static final int ERROR = 10;
  public static final int ID_COMP = 23;
  public static final int COLON = 8;
  public static final int LBRACE = 6;
  public static final int INDEX = 27;
  public static final int TITLE = 17;
  public static final int THEME = 19;
  public static final int ALING = 29;
  public static final int FORMS = 2;
  public static final int COLUMNS = 34;
  public static final int DATE_USER = 13;
  public static final int RBRACE = 7;
  public static final int E_DATE = 14;
  public static final int OPT = 32;
  public static final int TEXT = 28;
  public static final int DATE_FORM = 21;
  public static final int USER = 11;
  public static final int FALSE = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FORMS",
  "USERS",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "COLON",
  "COMMA",
  "ERROR",
  "USER",
  "PASS",
  "DATE_USER",
  "E_DATE",
  "NULL",
  "ID_FORM",
  "TITLE",
  "NAME",
  "THEME",
  "USER_C",
  "DATE_FORM",
  "COMP",
  "ID_COMP",
  "FIELD_N",
  "FORM_ID",
  "TIPO",
  "INDEX",
  "TEXT",
  "ALING",
  "REQUIRED",
  "URL",
  "OPT",
  "ROWS",
  "COLUMNS",
  "STR",
  "TRUE",
  "FALSE",
  "INTEGER"
  };
}

