
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cesar31.formsweb.parser.db;

/** CUP generated class containing symbol constants. */
public class DataParserSym {
  /* terminals */
  public static final int LBRACE = 4;
  public static final int COLON = 6;
  public static final int STR = 9;
  public static final int C_DATE = 12;
  public static final int USER = 10;
  public static final int NULL = 14;
  public static final int ERROR = 8;
  public static final int EOF = 0;
  public static final int RBRACKET = 3;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int PASS = 11;
  public static final int E_DATE = 13;
  public static final int LBRACKET = 2;
  public static final int RBRACE = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "COLON",
  "COMMA",
  "ERROR",
  "STR",
  "USER",
  "PASS",
  "C_DATE",
  "E_DATE",
  "NULL"
  };
}

